Default: &defaults
  database: taws.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: taws_test.sqlite3
  <<: *defaults

Staging:
  database: taws_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: taws_production.sqlite3
  poolsize: 100
  <<: *defaults
